### ISSUE TITLE
The Impact encoding is not done properly for the validation data for early stopping

### ISSUE THREAD

**Issue by ja-thomas** [ja-thomas/autoxgboost#25]
We only do this in the training of xgb early stopping, where the factors are already encoded

**Comment by Coorsaa** [comment]
is this still an issue @ja-thomas ?

**Comment by ja-thomas** [comment]
yes

**Comment by ja-thomas** [comment]
I think it might work in the following way when we switch over to CPOs

- We split our dataset before passing it to xgboost.earlystop
- Calculate the preprocs. on the training data and apply the trained CPO on the test data
- Pass the preprocessed test data as a parameter to xgboost.earlystop.

**Comment by ja-thomas** [comment]
fixed in  385f3cd
