### ISSUE TITLE
tune class weights param for unbalanced classif

### ISSUE THREAD

**Issue by ja-thomas** [ja-thomas/autoxgboost#35]
We're supporting weights, so class weights might be a nice way to improve the performance on unbalanced data.

But at some point it will get annoying with more and more wrapper, so we should def. consider mlrCPO

**Comment by ja-thomas** [comment]
We can just use the `scale_pos_weight` parameter

**Comment by ja-thomas** [comment]
done

**Comment by p-schaefer** [comment]
Unless I am mistaken, `scale_pos_weight ` is only for binary classification, is there an alternative for multiclass classifications? Perhaps with `xgboost.DMatrix(..., weight = *weight array for individual weights*)` or perhaps there is a better alternative?
