### ISSUE TITLE
min_child_weight missing in default parsets

### ISSUE THREAD

**Issue by giuseppec** [ja-thomas/autoxgboost#54]
In https://github.com/ja-thomas/autoxgboost/blob/master/R/autoxgbparset.R the is missing in both `autoxgbparset` and `autoxgbparset.mixed`. Is there a reason why?

**Comment by ja-thomas** [comment]
Yes, I didn't add all available parameters.
For this I'm really unsure about reasonable bounds and it is "just" another regularizer, so I'm unsure how important it actually is.

**Comment by giuseppec** [comment]
Ok, thx for clarification. In any case the user can extend the paramset anyway. I am therefeore closing this.
